{{- if .Values.detectors.tcpflowkiller.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cryptnono.fullname" . }}-tcpflowkiller
  labels:
    {{- include "cryptnono.labels" . | nindent 4 }}
data:
  flowkiller_config.json: |
    {{- .Values.detectors.tcpflowkiller.config | mustToPrettyJson | nindent 4 }}
{{- end }}
